---
- import_tasks: partition.yml

- include_tasks: lvmraid.yml
  when: raid_backend == 'lvmraid'

- include_tasks: mdraid.yml
  when: raid_backend == 'mdraid'

- name: Create VDO layer
  when: raid_create_vdo | bool
  block:
    - include_tasks: vdo_setup.yml

    - include_tasks: vdo_lvmraid.yml
      when: raid_backend == 'lvmraid'

    - include_tasks: vdo_mdraid.yml
      when: raid_backend == 'mdraid'

- include_tasks: mkfs.yml
  when: raid_create_fs | bool

- include_tasks: mount.yml
  when: raid_add_to_fstab | bool
