---
- name: Set partition flag for lvmraid
  ansible.builtin.set_fact:
    parted_flag: lvm
  when: raid_backend == 'lvmraid'

- name: Partition block devices
  community.general.parted:
    state: present
    device: /dev/{{ item }}
    label: gpt
    number: 1
    name: "{{ raid_name }}_member{{ idx }}"
    flags: [ "{{ parted_flag | default('raid') }}" ]
  loop: "{{ raid_block_devs }}"
  loop_control:
    index_var: idx
