---
- name: Add VDO layer
  community.general.vdo:
    state: present
    name: "{{ raid_vdo_name }}"
    device: "{{ raid_device }}"
    logicalsize: "{{ vdo_logicalsize }}B"
    slabsize: "{{ vdo_slabsize }}G"
    indexmode: "{{ vdo_indexmode | default('dense') }}"
    indexmem: "{{ vdo_indexmem }}"
    compression: enabled
    deduplication: enabled
  when: raid_vdo_name not in vdo_check.stdout

# Overwrite raid_device var
- name: Set raid_device
  ansible.builtin.set_fact:
    raid_device: /dev/mapper/{{ raid_vdo_name }}
