---
- name: Convert lvmraid to lvmvdo pool
  ansible.builtin.command:
    cmd: >
      lvconvert -y
        --type vdo-pool
        --virtualsize {{ vdo_logicalsize_mb }}M
        --name {{ raid_vdo_name }}
        --config 'allocation/vdo_use_sparse_index={{ vdo_use_sparse_index | default('0') }}
                  allocation/vdo_index_memory_size_mb={{ vdo_index_memory_size_mb }}
                  allocation/vdo_slab_size_mb={{ vdo_slab_size_mb }}'
        {{ raid_vg_name }}/{{ raid_lv_name }}
  when: raid_vdo_name not in ansible_lvm.lvs

# Overwrite raid_device var
- name: Set raid_device
  ansible.builtin.set_fact:
    raid_device: /dev/{{ raid_vg_name }}/{{ raid_vdo_name }}
